import { PrismaClient } from '../src/generated/prisma/client';
import { PrismaLibSql } from '@prisma/adapter-libsql';
import path from 'path';

const dbPath = process.env.DATABASE_PATH || path.join(process.cwd(), 'dev.db');
const adapter = new PrismaLibSql({ url: `file:${dbPath}` });
const prisma = new PrismaClient({ adapter });

function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

const now = new Date().toISOString();

const FIRMS = [
  {
    name: 'Sequoia Capital',
    description: 'Sequoia Capital is a legendary venture capital firm that has backed companies like Apple, Google, Airbnb, and Stripe. Known for partnering with founders from seed to growth stage across technology sectors.',
    website: 'https://www.sequoiacap.com',
    hq: 'Menlo Park, CA',
    stages: ['Seed', 'Series A', 'Series B', 'Growth'],
    sectors: ['Enterprise', 'Consumer', 'Fintech', 'Healthcare', 'AI/ML'],
    checkMin: '$100K', checkMax: '$100M+', fundSize: '$85B+ AUM',
    portfolio: ['Apple', 'Google', 'Airbnb', 'Stripe', 'WhatsApp', 'Zoom', 'DoorDash', 'Unity'],
    founded: '1972', teamSize: '200+', type: 'vc', featured: true,
  },
  {
    name: 'Andreessen Horowitz',
    description: 'a16z is a venture capital firm that backs bold entrepreneurs building the future through technology. They provide operational support through a dedicated portfolio services team spanning recruiting, marketing, and business development.',
    website: 'https://a16z.com',
    hq: 'Menlo Park, CA',
    stages: ['Seed', 'Series A', 'Series B', 'Growth'],
    sectors: ['AI/ML', 'Crypto', 'Enterprise', 'Fintech', 'Consumer', 'Bio/Health'],
    checkMin: '$500K', checkMax: '$100M+', fundSize: '$35B+ AUM',
    portfolio: ['GitHub', 'Coinbase', 'Slack', 'Figma', 'Instacart', 'Roblox', 'Databricks'],
    founded: '2009', teamSize: '180+', type: 'vc', featured: true,
  },
  {
    name: 'Y Combinator',
    description: 'Y Combinator is the world\'s most prolific startup accelerator. They invest $500K in startups twice a year and have funded over 4,000 companies including Airbnb, Stripe, and DoorDash.',
    website: 'https://www.ycombinator.com',
    hq: 'San Francisco, CA',
    stages: ['Pre-Seed', 'Seed'],
    sectors: ['SaaS', 'AI/ML', 'Fintech', 'Healthcare', 'Consumer', 'Enterprise', 'Dev Tools'],
    checkMin: '$500K', checkMax: '$500K', fundSize: 'N/A',
    portfolio: ['Airbnb', 'Stripe', 'DoorDash', 'Coinbase', 'Twitch', 'Reddit', 'Dropbox'],
    founded: '2005', teamSize: '50+', type: 'accelerator', featured: true,
  },
  {
    name: 'Accel',
    description: 'Accel is a global venture capital firm that invests in seed through growth-stage startups. Known for early bets on Facebook, Slack, and Atlassian.',
    website: 'https://www.accel.com',
    hq: 'Palo Alto, CA',
    stages: ['Seed', 'Series A', 'Series B'],
    sectors: ['SaaS', 'Enterprise', 'Consumer', 'Fintech', 'Security'],
    checkMin: '$1M', checkMax: '$50M', fundSize: '$3B+',
    portfolio: ['Facebook', 'Slack', 'Atlassian', 'Spotify', 'CrowdStrike', 'UiPath', 'Qualtrics'],
    founded: '1983', teamSize: '60+', type: 'vc', featured: true,
  },
  {
    name: 'Benchmark',
    description: 'Benchmark is an early-stage venture capital firm known for its equal partnership structure. They focus on seed and Series A investments with a hands-on approach.',
    website: 'https://www.benchmark.com',
    hq: 'San Francisco, CA',
    stages: ['Seed', 'Series A'],
    sectors: ['Consumer', 'Enterprise', 'Marketplaces', 'SaaS'],
    checkMin: '$1M', checkMax: '$20M', fundSize: '$425M per fund',
    portfolio: ['eBay', 'Twitter', 'Uber', 'Snapchat', 'Instagram', 'Discord', 'Zillow'],
    founded: '1995', teamSize: '10', type: 'vc', featured: true,
  },
  {
    name: 'Greylock Partners',
    description: 'Greylock Partners is one of the oldest venture capital firms in Silicon Valley, focused on enterprise and consumer technology. Known for their strong founder relationships.',
    website: 'https://greylock.com',
    hq: 'Menlo Park, CA',
    stages: ['Seed', 'Series A', 'Series B'],
    sectors: ['Enterprise', 'Consumer', 'AI/ML', 'Data Infrastructure'],
    checkMin: '$1M', checkMax: '$50M', fundSize: '$1B+',
    portfolio: ['LinkedIn', 'Airbnb', 'Discord', 'Figma', 'Roblox', 'Workday', 'Palo Alto Networks'],
    founded: '1965', teamSize: '30+', type: 'vc', featured: true,
  },
  {
    name: 'Lightspeed Venture Partners',
    description: 'Lightspeed invests in enterprise and consumer technology companies at every stage. Known for investments in Snap, Affirm, and Mulesoft.',
    website: 'https://lsvp.com',
    hq: 'Menlo Park, CA',
    stages: ['Seed', 'Series A', 'Series B', 'Growth'],
    sectors: ['Enterprise', 'Consumer', 'Fintech', 'Healthcare', 'Crypto'],
    checkMin: '$500K', checkMax: '$100M', fundSize: '$10B+ AUM',
    portfolio: ['Snap', 'Affirm', 'Mulesoft', 'Nutanix', 'AppDynamics', 'Grafana'],
    founded: '2000', teamSize: '80+', type: 'vc',
  },
  {
    name: 'First Round Capital',
    description: 'First Round Capital is a seed-stage venture firm based in San Francisco. They provide extensive community and operational resources to their portfolio founders.',
    website: 'https://firstround.com',
    hq: 'San Francisco, CA',
    stages: ['Pre-Seed', 'Seed'],
    sectors: ['SaaS', 'Enterprise', 'Consumer', 'Dev Tools', 'Fintech'],
    checkMin: '$500K', checkMax: '$3M', fundSize: '$700M+',
    portfolio: ['Uber', 'Square', 'Notion', 'Roblox', 'Warby Parker', 'Flatiron Health'],
    founded: '2004', teamSize: '40+', type: 'vc', featured: true,
  },
  {
    name: 'Bessemer Venture Partners',
    description: 'Bessemer is one of the oldest VC firms in the US, with a strong track record in cloud computing and enterprise SaaS. Known for their famous anti-portfolio of missed deals.',
    website: 'https://www.bvp.com',
    hq: 'San Francisco, CA',
    stages: ['Seed', 'Series A', 'Series B', 'Growth'],
    sectors: ['Cloud', 'SaaS', 'Healthcare', 'Consumer', 'Security'],
    checkMin: '$1M', checkMax: '$50M', fundSize: '$4B+',
    portfolio: ['Shopify', 'Twilio', 'LinkedIn', 'Pinterest', 'Canva', 'Toast', 'Fiverr'],
    founded: '1911', teamSize: '80+', type: 'vc',
  },
  {
    name: 'Kleiner Perkins',
    description: 'Kleiner Perkins has been backing breakthrough ideas for over 50 years, from the earliest days of the internet to the current AI revolution.',
    website: 'https://www.kleinerperkins.com',
    hq: 'Menlo Park, CA',
    stages: ['Seed', 'Series A', 'Series B'],
    sectors: ['AI/ML', 'Enterprise', 'Consumer', 'Healthcare', 'Fintech'],
    checkMin: '$1M', checkMax: '$25M', fundSize: '$1.5B+',
    portfolio: ['Amazon', 'Google', 'Twitter', 'Slack', 'Figma', 'Rippling', 'Nuro'],
    founded: '1972', teamSize: '40+', type: 'vc',
  },
  {
    name: 'Founders Fund',
    description: 'Founded by Peter Thiel, Founders Fund invests in companies building revolutionary technologies. They focus on "hard tech" and ambitious founders.',
    website: 'https://foundersfund.com',
    hq: 'San Francisco, CA',
    stages: ['Seed', 'Series A', 'Series B', 'Growth'],
    sectors: ['AI/ML', 'Aerospace', 'Defense', 'Biotech', 'Crypto', 'Enterprise'],
    checkMin: '$500K', checkMax: '$100M', fundSize: '$11B+',
    portfolio: ['SpaceX', 'Palantir', 'Stripe', 'Airbnb', 'Anduril', 'Figma'],
    founded: '2005', teamSize: '30+', type: 'vc',
  },
  {
    name: 'Index Ventures',
    description: 'Index Ventures is a global venture capital firm with offices in San Francisco, London, and Geneva. They invest across seed to growth in technology companies.',
    website: 'https://www.indexventures.com',
    hq: 'San Francisco, CA',
    stages: ['Seed', 'Series A', 'Series B', 'Growth'],
    sectors: ['Fintech', 'SaaS', 'Consumer', 'Gaming', 'Marketplaces'],
    checkMin: '$1M', checkMax: '$100M', fundSize: '$2.7B+',
    portfolio: ['Figma', 'Discord', 'Roblox', 'Notion', 'Plaid', 'Deliveroo', 'Revolut'],
    founded: '1996', teamSize: '80+', type: 'vc',
  },
  {
    name: 'General Catalyst',
    description: 'General Catalyst is a venture capital firm that invests in powerful, positive change. They focus on enterprise, consumer, and healthcare technology.',
    website: 'https://www.generalcatalyst.com',
    hq: 'Cambridge, MA',
    stages: ['Seed', 'Series A', 'Series B', 'Growth'],
    sectors: ['Enterprise', 'Healthcare', 'Fintech', 'Consumer', 'Insurance'],
    checkMin: '$500K', checkMax: '$100M', fundSize: '$25B+ AUM',
    portfolio: ['Stripe', 'Snap', 'Airbnb', 'HubSpot', 'Lemonade', 'Livongo'],
    founded: '2000', teamSize: '80+', type: 'vc',
  },
  {
    name: 'NEA (New Enterprise Associates)',
    description: 'NEA is one of the world\'s largest and most active venture capital firms, investing in technology and healthcare companies at all stages.',
    website: 'https://www.nea.com',
    hq: 'Menlo Park, CA',
    stages: ['Seed', 'Series A', 'Series B', 'Growth'],
    sectors: ['Enterprise', 'Healthcare', 'Consumer', 'Fintech'],
    checkMin: '$250K', checkMax: '$100M+', fundSize: '$25B+ AUM',
    portfolio: ['Salesforce', 'Workday', 'Uber', 'Cloudflare', 'Robinhood', 'Plaid'],
    founded: '1977', teamSize: '100+', type: 'vc',
  },
  {
    name: 'Tiger Global',
    description: 'Tiger Global is a New York-based investment firm that focuses on growth-stage technology investments with a fast, high-conviction approach.',
    website: 'https://www.tigerglobal.com',
    hq: 'New York, NY',
    stages: ['Series A', 'Series B', 'Growth'],
    sectors: ['SaaS', 'Fintech', 'Consumer', 'E-commerce', 'AI/ML'],
    checkMin: '$10M', checkMax: '$500M', fundSize: '$50B+ AUM',
    portfolio: ['Stripe', 'Shopify', 'Notion', 'Figma', 'Toast', 'Databricks'],
    founded: '2001', teamSize: '150+', type: 'vc',
  },
  {
    name: 'Khosla Ventures',
    description: 'Khosla Ventures invests in both early and growth stage companies in sectors like AI, sustainability, healthcare, and enterprise. Founded by Sun Microsystems co-founder Vinod Khosla.',
    website: 'https://www.khoslaventures.com',
    hq: 'Menlo Park, CA',
    stages: ['Seed', 'Series A', 'Series B'],
    sectors: ['AI/ML', 'Climate', 'Healthcare', 'Enterprise', 'Fintech'],
    checkMin: '$250K', checkMax: '$50M', fundSize: '$15B+',
    portfolio: ['OpenAI', 'Stripe', 'Square', 'DoorDash', 'Instacart', 'Impossible Foods'],
    founded: '2004', teamSize: '40+', type: 'vc',
  },
  {
    name: 'Insight Partners',
    description: 'Insight Partners is a global software investor and operator. They focus on scaling software companies from growth stage through IPO.',
    website: 'https://www.insightpartners.com',
    hq: 'New York, NY',
    stages: ['Series B', 'Growth'],
    sectors: ['SaaS', 'Enterprise', 'Security', 'Data', 'Dev Tools'],
    checkMin: '$10M', checkMax: '$200M', fundSize: '$90B+ AUM',
    portfolio: ['Shopify', 'Twitter', 'Monday.com', 'SentinelOne', 'Veeam', 'Wiz'],
    founded: '1995', teamSize: '100+', type: 'vc',
  },
  {
    name: '500 Global',
    description: '500 Global (formerly 500 Startups) is a global venture capital firm with one of the most active and diverse early-stage portfolios, having invested in 2,800+ companies across 80+ countries.',
    website: 'https://500.co',
    hq: 'San Francisco, CA',
    stages: ['Pre-Seed', 'Seed'],
    sectors: ['SaaS', 'Fintech', 'Consumer', 'E-commerce', 'EdTech'],
    checkMin: '$50K', checkMax: '$500K', fundSize: '$2.7B+',
    portfolio: ['Canva', 'Grab', 'Talkdesk', 'Credit Karma', 'Udemy', 'GitLab'],
    founded: '2010', teamSize: '100+', type: 'accelerator',
  },
  {
    name: 'Techstars',
    description: 'Techstars is a global accelerator network that helps entrepreneurs succeed. They run accelerator programs in cities worldwide and invest in early-stage startups.',
    website: 'https://www.techstars.com',
    hq: 'Boulder, CO',
    stages: ['Pre-Seed', 'Seed'],
    sectors: ['SaaS', 'AI/ML', 'Fintech', 'Healthcare', 'Climate', 'Consumer'],
    checkMin: '$120K', checkMax: '$120K', fundSize: 'N/A',
    portfolio: ['SendGrid', 'Sphero', 'ClassPass', 'Pillpack', 'DataRobot'],
    founded: '2006', teamSize: '200+', type: 'accelerator',
  },
  {
    name: 'Ribbit Capital',
    description: 'Ribbit Capital is a fintech-focused venture firm that invests in companies reimagining financial services through technology.',
    website: 'https://ribbitcap.com',
    hq: 'Menlo Park, CA',
    stages: ['Seed', 'Series A', 'Series B'],
    sectors: ['Fintech', 'Insurance', 'Payments', 'Crypto', 'Banking'],
    checkMin: '$1M', checkMax: '$50M', fundSize: '$1.5B+',
    portfolio: ['Robinhood', 'Nubank', 'Coinbase', 'Credit Karma', 'Revolut', 'Affirm'],
    founded: '2012', teamSize: '15', type: 'vc',
  },
  {
    name: 'Craft Ventures',
    description: 'Craft Ventures is a seed and early-stage venture capital firm founded by David Sacks. They focus on enterprise SaaS and marketplace companies.',
    website: 'https://www.craftventures.com',
    hq: 'San Francisco, CA',
    stages: ['Seed', 'Series A'],
    sectors: ['SaaS', 'Enterprise', 'Marketplaces', 'Fintech', 'AI/ML'],
    checkMin: '$1M', checkMax: '$15M', fundSize: '$2B+',
    portfolio: ['SpaceX', 'Neuralink', 'Bird', 'ClickUp', 'Sourcegraph'],
    founded: '2017', teamSize: '20+', type: 'vc',
  },
  {
    name: 'Lux Capital',
    description: 'Lux Capital invests in emerging science and technology ventures at the outermost edges of what is possible. They focus on deep tech and frontier technology.',
    website: 'https://www.luxcapital.com',
    hq: 'New York, NY',
    stages: ['Seed', 'Series A', 'Series B'],
    sectors: ['Deep Tech', 'AI/ML', 'Robotics', 'Healthcare', 'Aerospace', 'Defense'],
    checkMin: '$1M', checkMax: '$30M', fundSize: '$4.6B+',
    portfolio: ['Anduril', 'Flexport', 'Saildrone', 'Desktop Metal', 'Kurion'],
    founded: '2000', teamSize: '30+', type: 'vc',
  },
  {
    name: 'Redpoint Ventures',
    description: 'Redpoint Ventures has partnered with visionary founders to create new markets and redefine existing ones. They invest across consumer, infrastructure, and enterprise.',
    website: 'https://www.redpoint.com',
    hq: 'San Francisco, CA',
    stages: ['Seed', 'Series A', 'Series B'],
    sectors: ['Enterprise', 'Consumer', 'Infrastructure', 'Fintech'],
    checkMin: '$1M', checkMax: '$50M', fundSize: '$6B+',
    portfolio: ['Netflix', 'Stripe', 'Snowflake', 'Twilio', 'HashiCorp', 'Ramp'],
    founded: '1999', teamSize: '40+', type: 'vc',
  },
  {
    name: 'Union Square Ventures',
    description: 'USV is a thesis-driven venture capital firm investing in networks, platforms, and protocols. Known for early bets on the internet, blockchain, and crypto economy.',
    website: 'https://www.usv.com',
    hq: 'New York, NY',
    stages: ['Seed', 'Series A'],
    sectors: ['Crypto', 'Marketplaces', 'Consumer', 'Climate', 'Healthcare'],
    checkMin: '$1M', checkMax: '$25M', fundSize: '$1.5B+',
    portfolio: ['Twitter', 'Etsy', 'Coinbase', 'Cloudflare', 'MongoDB', 'Duolingo'],
    founded: '2003', teamSize: '15', type: 'vc',
  },
  {
    name: 'Initialized Capital',
    description: 'Initialized Capital is an early-stage venture fund co-founded by Garry Tan (now YC President) and Alexis Ohanian (Reddit co-founder). They invest at pre-seed and seed.',
    website: 'https://initialized.com',
    hq: 'San Francisco, CA',
    stages: ['Pre-Seed', 'Seed'],
    sectors: ['SaaS', 'AI/ML', 'Consumer', 'Dev Tools', 'Enterprise'],
    checkMin: '$250K', checkMax: '$3M', fundSize: '$700M+',
    portfolio: ['Coinbase', 'Instacart', 'Cruise', 'Flexport', 'Rippling'],
    founded: '2012', teamSize: '15', type: 'vc',
  },
  {
    name: 'a][ Capital',
    description: 'Abstract Capital invests in early-stage startups across the Middle East, North Africa, and emerging markets. They focus on technology-enabled companies.',
    website: 'https://www.abstractcapital.com',
    hq: 'Dubai, UAE',
    stages: ['Pre-Seed', 'Seed', 'Series A'],
    sectors: ['Fintech', 'E-commerce', 'SaaS', 'Logistics', 'Consumer'],
    checkMin: '$100K', checkMax: '$2M', fundSize: '$50M+',
    portfolio: [],
    founded: '2019', teamSize: '10', type: 'vc',
  },
  {
    name: 'STV',
    description: 'STV is a leading venture capital firm in the Middle East backed by Saudi Aramco. They invest in technology companies across the MENA region and globally.',
    website: 'https://stv.vc',
    hq: 'Riyadh, Saudi Arabia',
    stages: ['Seed', 'Series A', 'Series B'],
    sectors: ['Fintech', 'E-commerce', 'Enterprise', 'EdTech', 'Logistics'],
    checkMin: '$500K', checkMax: '$20M', fundSize: '$500M+',
    portfolio: ['Tamara', 'Trukker', 'Foodics', 'Nana', 'Lean Technologies'],
    founded: '2018', teamSize: '20+', type: 'vc',
  },
  {
    name: 'BECO Capital',
    description: 'BECO Capital is a Dubai-based venture capital firm investing in technology startups across the MENA region from seed to Series B.',
    website: 'https://www.becocapital.com',
    hq: 'Dubai, UAE',
    stages: ['Seed', 'Series A', 'Series B'],
    sectors: ['Fintech', 'Healthcare', 'E-commerce', 'Logistics', 'Enterprise'],
    checkMin: '$500K', checkMax: '$10M', fundSize: '$250M+',
    portfolio: ['Careem', 'Bayzat', 'Swvl', 'Kitopi', 'Property Finder'],
    founded: '2012', teamSize: '15', type: 'vc',
  },
  {
    name: 'Atomico',
    description: 'Atomico is a European venture capital firm founded by Skype co-founder Niklas Zennstrom. They invest in ambitious tech founders building global companies from Europe.',
    website: 'https://www.atomico.com',
    hq: 'London, UK',
    stages: ['Series A', 'Series B', 'Growth'],
    sectors: ['Enterprise', 'Consumer', 'Fintech', 'Healthcare', 'Climate'],
    checkMin: '$5M', checkMax: '$100M', fundSize: '$4.8B+',
    portfolio: ['Klarna', 'Graphcore', 'Supercell', 'MessageBird', 'Hims & Hers'],
    founded: '2006', teamSize: '60+', type: 'vc',
  },
  {
    name: 'Balderton Capital',
    description: 'Balderton Capital is a European venture capital firm focused on Series A and Series B investments. They back European founders building global businesses.',
    website: 'https://www.balderton.com',
    hq: 'London, UK',
    stages: ['Series A', 'Series B'],
    sectors: ['SaaS', 'Fintech', 'Consumer', 'Healthcare', 'Marketplaces'],
    checkMin: '$5M', checkMax: '$30M', fundSize: '$4B+',
    portfolio: ['Revolut', 'Citymapper', 'Nutmeg', 'Aircall', 'Contentful'],
    founded: '2000', teamSize: '40+', type: 'vc',
  },
];

async function main() {
  console.log(`Seeding ${FIRMS.length} public firms...`);

  for (const firm of FIRMS) {
    const slug = slugify(firm.name);
    await prisma.publicFirm.upsert({
      where: { slug },
      update: {
        name: firm.name,
        description: firm.description,
        website: firm.website,
        hq: firm.hq,
        stages: JSON.stringify(firm.stages),
        sectors: JSON.stringify(firm.sectors),
        checkMin: firm.checkMin,
        checkMax: firm.checkMax,
        fundSize: firm.fundSize,
        portfolio: JSON.stringify(firm.portfolio),
        founded: firm.founded,
        teamSize: firm.teamSize,
        type: firm.type,
        featured: firm.featured || false,
        updatedAt: now,
      },
      create: {
        slug,
        name: firm.name,
        description: firm.description,
        website: firm.website,
        hq: firm.hq,
        stages: JSON.stringify(firm.stages),
        sectors: JSON.stringify(firm.sectors),
        checkMin: firm.checkMin,
        checkMax: firm.checkMax,
        fundSize: firm.fundSize,
        portfolio: JSON.stringify(firm.portfolio),
        founded: firm.founded,
        teamSize: firm.teamSize,
        type: firm.type,
        featured: firm.featured || false,
        createdAt: now,
        updatedAt: now,
      },
    });
    console.log(`  + ${firm.name} (${slug})`);
  }

  console.log('Done!');
}

main().catch(console.error).finally(() => prisma.$disconnect());
